### ISSUE TITLE
channel member page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1249]
As a user, I'd like to be able to see who else is a member of the current channel. 

See https://zpl.io/25rzyx8

We'll add a tab and, eventually, a widget that links to this page. 

### acceptance criteria
- [ ] add tab to channel page
- [ ] card for each user
- [ ] label for moderators (design pending)
- [ ] sort by date joined, number of comments
- [ ] filter to show only moderators

### related issues:
- #1063 updates to member API
- #1054 members widget

**Comment by rhysyngsun** [comment]
A few issues that came up in planning:

- We currently have an API to get a list of contributors, but that doesn't work for public channels, because contributors aren't a factor there. What we _probably_ want is subscribers since that works across all channel types, but this largely depends on what we want our definition of "members" to be.
- Reddit doesn't have an API to get a listing of subscribers of a channel (hence we don't have an API for this either). We would need to mirror subscriber data in the discussions DB to get this information, including count.

**Comment by pdpinch** [comment]
This was address by #1936
