### ISSUE TITLE
Sign up: RequireProviderException

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1364]
This happened to @loemerdotcom  (see https://sentry.io/mit-office-of-digital-learning/discussions/issues/696896111/events/33113771830/) but I haven't been able to reproduce it myself.

I'm also not sure why there have been so many users creating accounts already.  

https://sentry.io/mit-office-of-digital-learning/discussions/issues/696896111/

```
RequireProviderException: 
(7 additional frame(s) were not displayed)
...
  File "rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "authentication/serializers.py", line 223, in create
    result = super()._authenticate(SocialAuthState.FLOW_REGISTER)
  File "authentication/serializers.py", line 82, in _authenticate
    user = backend.complete(user=user, **kwargs)
  File "social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "authentication/pipeline/user.py", line 236, in require_micromasters_provider
    raise RequireProviderException(backend, social_auth)

Received unexpected AuthException
```

**Comment by rhysyngsun** [comment]
This exception is getting raised when a user only has one social auth and it's micromasters. This is used on the login side to prompt the user to login via MM instead of password, but it's erroring here when someone tries to signup for an account already registered to a MM user. Basically, this is a special case of a signup for an account that technically already exists.

The quickest fix would be to catch this error and return an appropriate response to the frontend so it can redirect them to the login form and prompt them to login via MM.
