### ISSUE TITLE
Create an API call for getting a list of followers for a channel

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#1466]
Part of Epic #1420

**Comment by mbertrand** [comment]
@pdpinch @noisecapella I'm wondering what kind of object makes the most sense to return in this list:

- `User` (object or serialized data)
- `Profile` (object or serialized data)
- `User.username` strings
- `Redditor` (object or serialized data)

If it's only going to be used as a filter for searches, then username strings should be adequate.

**Comment by mbertrand** [comment]
FWIW, the current `channels.api.Api` currently has `list_contributors` and `list_moderators` methods that both return lists of `Redditor` objects.   I'm assuming I should add a `list_subscribers` method that returns subscribers, and a `list_followers` method that returns all 3 (contributors, moderators, subscribers).

**Comment by pdpinch** [comment]
followers and subscribers are synonyms. The UI will say "follow" and "unfollow" but so far it looks like our data model will follow the naming from reddit, "subscribers" So one API should be sufficient. 

Just because someone is a moderator does not necessarily mean that they are a subscriber/follower. I think the `list_subscribers` method should only return subscribers. 

I'm not sure what to do about the return. I think we want to be moving away from object types that are tied to reddit, but I'm not sure how much of that you want to take on in this issue.
