### ISSUE TITLE
Hide site logo on intro card in mobile view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1484]
See https://zpl.io/aBNlnlQ

Similar to how we had the channel avatar on mobile view.

**Comment by aliceriot** [comment]
question on this, on the zeplin design above the not-logged-in text on the button is "sign up", currently on master it's "become a member". Changing to "sign up" makes it easier to get a nice responsive layout for the card, because the button has less text in it. Which do we want to go with? I see "Become a member" on other designs on Zeplin.
