### ISSUE TITLE
Remove channel title from channel settings

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1537]
As the site owner, I don't want channel moderators changing their channel titles without review -- in order to avoid name collisions, duplicate branding and an extra-wide side nav menu. 

### acceptance criteria
- [ ] make the title field in the channel settings "appearance" tab read only
- [ ] below the title, add the text "Need to change the channel title? Contact Us" 
- [ ] "Contact Us" have a mailto link to the support address
- [ ] remove the title from the channel settings API, just to be safe

### Questions
- As an admin, how can I easily change the title of a channel? Is it easier to add that to the django admin or add an admin-only permission to the channel settings form?

### related issues
- in the future, we may want a separate "long tile" for the channel header and a "short title" for the left hand nav

**Comment by rhysyngsun** [comment]
I'd suggest keeping the title field in the UI but only displaying it for staff users and guarding it against modification on the backend by non-staff users. In addition, we need to make sure that creating channels still works as expected through the staff web form and for micromasters. This would probably also be easier than putting it in django-admin since it's reddit-oriented and doesn't slot in nicely to a model admin view.
