### ISSUE TITLE
Article: save text to reddit

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1550]
Since we are using the text type of reddit post for article, we can save out a text version of the article into reddit. This may be useful for things like a post preview on the post summary card. 

Once we've figured out the text version of articles for search purposes, we can leverage that work for this.

**Comment by noisecapella** [comment]
This will be tricky because it looks like the frontend code uses the presence of text to determine whether or not it's an article post or a text post. In order to store the text in reddit we would need to update the model to store whether or not the post is an article or text post. If the goal is to provide a post preview for the compact post view we can do that in our view without making any changes to the information stored in reddit.

**Comment by pdpinch** [comment]
@rhysyngsun is that correct that we're using the presence of text to differentiate between an article post and a text post? 

Does that mean that we can't add any new post types without some significant back-end work? 

This issue isn't critical -- I just thought it would be convenient to do while we were working on Article search. But I would like to understand the implications better.

**Comment by pdpinch** [comment]
We decided to approach this differently, by adding a post_type and article_text to the posts api (issues #1635 and #1636 and PR #1633). This avoids the need to synchronize the text in reddit with the article.
