### ISSUE TITLE
Deleting newly added widgets doesn't work properly

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1626]
https://github.com/mitodl/open-discussions/pull/1598#issuecomment-450967187

**Comment by aliceriot** [comment]
copied for posterity:

I think this is totally unrelated to the changes in this PR, but I just noticed that clicking the 'delete' icon on any single widget in the 'editing' mode will delete all widgets which haven't yet been saved to the backend. It looks like this is happening because the widgets which haven't been saved yet do not have an `.id` property yet, and the `deleteInstance` method on the `WidgetListContainer` uses that prop to figure out which widgets to delete (in the case of not-yet-saved ones the value of this property will be `undefined`, which will then match every other not-yet-saved widget).

does it make sense to take care of that little bug in this PR, or should we file an issue?
