### ISSUE TITLE
Compact post summary card displays raw markdown

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1739]
This should probably either be plaintext or rendered

![screenshot_2019-01-17 profile for nathan levesque mit open learning](https://user-images.githubusercontent.com/28598/51342216-47c8c280-1a61-11e9-99b6-0a052242f34b.png)

**Comment by gsidebo** [comment]
@rhysyngsun I'm pretty sure we want to avoid rendering it. If the text has line breaks or large header elements it will look pretty rough in a post listing. It looks like we don't serialize the plain text for a post with markdown like we do for articles. I'm guessing that ideally this fix would involve serializing that plaintext in our API (like we seem to be doing for articles) rather than leaving it to be stripped out in JS. Let me know if you have any thoughts on that

**Comment by pdpinch** [comment]
I don't understand why this isn't rendered the same way it on a listing page?

**Comment by pdpinch** [comment]
Oh, I see. This is the post summary card with the content preview -- not post detail.
