### ISSUE TITLE
related content card on post detail page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1748]
As a user, I'd like to know about content on MIT Open that's similar to what I'm currently viewing on a post detail page. 

See https://zpl.io/2ZzODOd

### acceptance criteria
- [ ] behind a feature flag; when flag is false, only visible to django staff
- [ ] use elastic search to find similar text, link and article posts (not users, channels or courses)
- [ ] configurable set of results, defaulting to 4
- [ ] Display post title, author and channel for all posts
  - [ ] link title to post detail
  - [ ] link author to author profile
  - [ ] link channel to channel 
- [ ] display link icon and off-site link for link posts

### nice to have
- [ ] boot posts with higher votes and comments

**Comment by gsidebo** [comment]
@pdpinch This is an edge case if we consider all posts in the same channel as related, but it's still possible to have a post with no related content. Do we want to hide that column if no related posts exist?

**Comment by pdpinch** [comment]
Sure. Makes sense. 

> Do we want to hide that column if no related posts exist?

**Comment by gsidebo** [comment]
Should have phrased that better. It's going to be easier in terms of implementation to leave the two column layout whether related posts exist or not. If it's not something we really care about we should probably leave it as-is

**Comment by Ferdi** [comment]
@gsidebo  I'm guessing ES should always return something as "similar" to the given doc.  Is that correct ?

**Comment by gsidebo** [comment]
@Ferdi The query defaults to looking in every single text field in the document for similar content, but I think we should avoid that so it doesn't become too arbitrary (example: if some post has an author with the same first name as the author of the post I'm looking at, that shouldn't boost the related content score). ES lets you pass in specific fields to inspect, so that's what I'm doing. I'm looking in these fields right now: `"plain_text", "post_title", "author_id", "channel_name"`. The only case I can think of when we will have no related posts is if a channel has only 1 post and none of the other fields match. It's an edge case for sure, but I was also asking in case we decide to change the fields that we want to match in the future.

**Comment by Ferdi** [comment]
@gsidebo great.  Not sure what should happen in the edge case you describe. up to you.
