### ISSUE TITLE
Allow email search for profiles for moderators

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1840]
Part of #1655 

Enabling email search is actually somewhat complicated because we do not index email addresses at all currently. We can't just put the email address in the serializer because we don't want to make it public information. To have this information be available to only certain users we need to think about who gets to see the email addresses and when, and how to enforce that via Elasticsearch.

#### Acceptance Criteria:

- [ ] Determine who can access what email addresses
 - [ ] Add email information to the indexing, with a whitelist filter of fields to prevent most users from seeing that field in Elasticsearch
- [ ] Implement email search on frontend

**Comment by pdpinch** [comment]
When I wrote the requirements for #1655 I was under the impression that searching by email would be easier and that searching by name would be the challenge. I understand now I had that backwards. 

There isn't much added user value for allowing search by email and I agree that it is fraught, from a privacy perspective.

I agree with closing this, but I appreciate having it scoped.

**Comment by rhysyngsun** [comment]
Another piece that probably needs to look into is how to disallow filtering by email by non-moderator users since that allows them to associate accounts by email. That might be a little tricky since we just let the frontend send whatever search criteria it wants. I think the only way to really address all of these safely and comprehensively is to implement field-level security on the ES side: https://www.elastic.co/guide/en/x-pack/current/field-and-document-access-control.html
