### ISSUE TITLE
Course Search: Hide channel navigation drawer while in course search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1889]
As a user, I find channel listings confusing when I'm doing a course search. it should be hidden. 

We probably want a unique template for the course search page. In particular, this would allow us to have some sub-branding for this page (e.g. "MIT Open | Courses" or similar) 

#### Designs and Mockups

None yet

#### Acceptance Criteria:

- [ ] hide the drawer when doing a course search

**Comment by mbertrand** [comment]
@pdpinch @ferdi how does this look? It's not quite a "unique" template, I updated the code so that the drawer, associated menu icon, and search icon in the `Toolbar` are hidden if the URL starts with `/courses` and made the `Toolbar` title customizable so that the default can be overridden.

<img width="875" alt="screen shot 2019-03-08 at 7 38 31 am" src="https://user-images.githubusercontent.com/187676/54029216-a7943d80-4175-11e9-9c94-9782ef7b83c2.png">

**Comment by mbertrand** [comment]
One thing I'm wondering though is if there should be any navigation links somewhere between this and the rest of the site.

**Comment by Ferdi** [comment]
Looks great. We have not figured out how to connect the two. It's ok though

**Comment by mbertrand** [comment]
Thanks, one more question - should the title ("MIT Open | Courses") still be a link and if so should it just link to the course search page for now (and eventually to the course index page when that is implemented)?

**Comment by Ferdi** [comment]
Ideally the "MIT OPEN" Part would like to open.mit.edu and "Courses" links to open.mit.edu/courses, the page the @aliceriot is working on.
