### ISSUE TITLE
Omit MITx "DELETE" courses from course database

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1930]
### Steps to Reproduce

1. Go to course search, populated with all the courses in the MITx feed. 
2. Search on DELETE
3. A number of "junk" courses are in the search results. 

### Expected Behavior

No courses with a title of DELETE should show up in the results. Just an OCW course on Syntax. 

### Actual Behavior

I see six "DELETE" courses in the results. 

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/54604931-6413bc00-4a1e-11e9-9822-40af4165067d.png)

**Comment by kyfantaz** [comment]
Hypothesis: 
To remove the search results and keep it removed, we'll need to:
1) Delete the Course instances for the six courses of interest (or an alternative such as setting their instance `Course.published` to `False`) as well as their index objects.
2) Prevent those Courses by being ingested again at the next data sync with a code change to `course_catalog.task_helpers`

We should find out where these courses are coming from OCW or edX. A quick google search reveals that "[DELETE]Management in Engineering II" comes from edX. To verify whether any of these are coming from OCW, l will need renewed S3 bucket access to the OCW bucket. Unless we discover otherwise, our code change will assume that these "deleted" courses could be coming either input source.

The code change could skip saving and indexing these courses in question. A simple code change could look at the title---it looks like the word "delete" is found in the Course title for the six concerned courses. The code to detect this could look like:
```python
def should_skip_course(course):
    """ skips of '[delete]', 'delete ' (note the ending space character) exists in course title or if the course title equals 'delete' """
    title = course.title.lower()
    if ("[delete]" in course_title) or ("delete " in title) or (title == "delete"):
        return True
    return False
```
which can be called in the sync task functions.

The "Introduction to Syntax" might be included in the current search query because it has the word "delete" indexed for search elsewhere such as the course description.

**Comment by pdpinch** [comment]
Thanks Kevin. The courses in question are in the edX feed. The rest of your assessment makes sense. 

I'll still get your access to the OCW content bucket renewed, but you shouldn't find any courses in there that need to be skipped.

**Comment by kyfantaz** [comment]
Got it. No need for OCW bucket access then, as I would only need access for testing.
