### ISSUE TITLE
People Widget: link to all members view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1932]
As a channel follower, I'd like to be able to see who else is a member of the channel. 

As a channel moderator, I'd like to see who is following my channel, especially people who have recently started following. This will give me a way to acknowledge new followers. 

#### Designs and Mockups

There is a UX video at https://drive.google.com/file/d/1-PBt3UO4wpVuRlL5gFZMS9kQgJGjUOHi/view?usp=sharing

The Members tab itself is mocked up at https://zpl.io/agnKAMO

#### Acceptance Criteria:

- [x] link to "All members" opens "Members" tab
- [ ] add "Members" tab to channel nav
- [x] view of all members in the channel (provided by search API?)
- [ ] default sort is alphabetical
- [ ] sort newest to old and oldest to newer
- [ ] unique URL route for when the members tab is open

#### out of scope

- filter by moderators (how hard is this?)
- sort by comments (how hard is this?)

**Comment by aliceriot** [comment]
the video doesn't seem to show what the 'all members' page should look like, is there a mockup of that?

**Comment by aliceriot** [comment]
I see this one: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5ba4e8bbf0f698a151986fd8

**Comment by pdpinch** [comment]
That's it. I updated the description to better describe the "Members" tab.

Do you think we can use the search API to populate the members tab? Sorting by the date they joined the channel is highly desirable -- but I'm not sure if we have the indexing in place to do that.

**Comment by aliceriot** [comment]
I'll take a look, I'm not super familiar with the search stuff for profiles but I'll poke at it and see what it gives us

**Comment by aliceriot** [comment]
for the APIs we might want to use for backing this it looks like we already have implemented a 'subscribers' API. I played around with this a little and confirm that it returns the user IDs of all the people subscribed to the channel, which is what I think we'd want for this (also I could be mis-remembering the distinction between contributors and subscribers).

I think we'd need to modify that API to also return information about the users' profiles though, in order to render the UI shown in the mockups, since right now it just returns the usernames. Alternatively we could implement a bulk profile API which takes a list of usernames and returns the profiles for them.

I haven't yet looked into using the search index to get the same data, but I'm going to poke at that today.

**Comment by aliceriot** [comment]
ok so it looks like it's possible to get all the information we need for this view from the search index we already have, by just passing a `channelName` and only getting results for the `profile` type.

**Comment by aliceriot** [comment]
it seems though that there's not an easy way with elasticsearch to get all the results, so we'd have to have some paging with an infinite scroll setup (like we have elsewhere)

**Comment by aliceriot** [comment]
I threw together a basic mockup / proof of concept using the search index to drive the page: 

![basic_mockup](https://user-images.githubusercontent.com/6207644/55010463-93946c80-4fba-11e9-8a52-1ad70e65a041.png)

**Comment by Ferdi** [comment]
Looks good. We will keep the main nav menu in this page right ?   Yes ,  we need pager or infinite scroll.

**Comment by aliceriot** [comment]
I think we should keep the main nav here - or do you mean the top navbar on the channel page, like shown here?

![channelnav](https://user-images.githubusercontent.com/6207644/55011909-fedf3e00-4fbc-11e9-9744-b55e7539ab6d.png)

if so I was planning to add that but just haven't made the change yet. the mockup above is currently using the infinite scroll that we use elsewhere, but just fetching results 100 at a time instead of our normal page size.

**Comment by Ferdi** [comment]
- I mean "home, About" 
- 100 a bit high but up to you. not sure how that affect performance etc.
