### ISSUE TITLE
API for making posts "sticky"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#194]
As a moderator, I'd like to be able to specify that certain posts are pinned to the top of the list. 

This can be done using [PRAW's `sticky()` API](https://github.com/praw-dev/praw/blob/bc2eb71572344327afe5663136f07f1df6357ffc/praw/models/reddit/submission.py#L381)

**Comment by pdpinch** [comment]
@rhysyngsun will this requires changes to the channel API?

**Comment by rhysyngsun** [comment]
@pdpinch I tested and verified that stickying a post does not move it to the top of the posts list. There is a separate reddit API that would need to be conditionally called if you are on the frontpage. Reddit itself only displays announcements if you're on the subreddit and have not paginated. It distinguishes these as not part of the posts list (note that they don't have a number to the left of the post). I would actually have this as part of a separate API so that we can reduce the number of times we're retrieving this data only to page loads of `/channel/channelname`
