### ISSUE TITLE
UI for adding and removing a course search result as a favorite

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2091]
As a user searching for courses, I'd like to be able to favorite results so I can easily find them later

#### Designs and Mockups

https://projects.invisionapp.com/d/main#/console/17477251/367253747/preview

#### Acceptance Criteria:

- [ ] As a logged in user, I should be able to add a search result to my favorites
- [ ] As a logged in user, I should be able to remove a search result from my favorites

#### Out of Scope

- For a first pass, we should just focus on the toggle of favorite on/off and not address the popup/user list UI

**Comment by rhysyngsun** [comment]
@pdpinch @abdulkdawson Do we have an idea what the experience should be for anonymous users since they won't be able to toggle favorites? Would it be the same signup/login popup that anonymous users get when they try to create a post?

**Comment by aliceriot** [comment]
one other question: currently for the course cards that we show on the home page clicking anywhere on the card opens the side drawer, which shows details for the course. Based on the mockups it seems that clicking on the star in the corner should favorite / unfavorite a course.

my question is, how should we change how we open the course details drawer? we could potentially change it so that only clicking the title, for instance, opens the detail drawer, or make it so that clicking anywhere except on the 'favorite' star will open the drawer.

**Comment by abdulkdawson** [comment]
@aliceriot Yes The entire card should not activate the drawer. Clicking the course title or thumbnail should open the drawer.

**Comment by abdulkdawson** [comment]
@rhysyngsun since the favorites are for signed in users I feel we should be prompting users to sign-up/login in order to utilize favorites. That to me is the best course of action.
