### ISSUE TITLE
When changing a vote, update the front-end so it's consistent with user expectations. 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#216]
as a user, I want to see the vote number change (immediately) when I change my vote. 

- [ ] 1. When adding an upvote, the vote should increase by one
- [ ] 2. When removing an upvote, the vote should decrease by one
- [ ] 3. When adding a downvote, the vote should decrease by one
- [ ] 4. When removing a downvote, the vote should increase by one
- [ ] 5. When switching a vote from an upvote to a downvote, the vote should decrease by two (combination of 2 and 4 above)
- [ ] 6. When switching a vote from an downvote to a upvote, the vote should increase by two (combination of 1 and 3 above)

I realize that the backend algorithm may behave differently for other users.

**Comment by aliceriot** [comment]
yeah reddit does the vote fuzzing so that it never returns the exact number of votes. I think @noisecapella has done some thinking about this as well.

My thinking it that we should probably just display to the user what the reddit backend displays for MVP, because to do something like what is described here (modifying the display value to override the value from the backend) is significantly more complicated, it means that for every comment, post, etc we have to keep track of whether a user has already voted on it, what the display value was when they voted on it, etc. Then when display the value we have to worry about whether to show that value or the actual value coming back from the backend, etc. So implementing something like this adds quite a bit of frontend complexity, which is definitely doable but I don't necessarily think we should take this on for MVP when we have other stuff to focus on.

An alternative is if we can disable the vote fuzzing in Reddit, I haven't looked into that but to me that's definitely the simplest way forward.

**Comment by aliceriot** [comment]
Interested in @roberthouse54 's thoughts on this too - what sort of UX would you expect for upvoting downvoting to have as far as the vote score goes?

**Comment by roberthouse54** [comment]
I like the idea of disabling the vote fuzzing, and just making the number be the votes count, although this would get rid of the concept of "freshness" factoring into the number (I think). Although I am not really clear on what the number is coming from or how it is computed.

**Comment by pdpinch** [comment]
We're overthinking this. 

Replaced by #220 and #221
