### ISSUE TITLE
When loading the course search directly, the loading placeholder for discussions channels appears

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2167]
### Steps to Reproduce
If you hit the search directly and it's slow to load, you'll see the loading placeholder for posts appear. We probably should have one for search tiles too.

e.g. http://od.odl.local:8063/courses/search?p=ocw

### Expected Behavior

(Optional)

### Actual Behavior

(Optional)

### Stacktrace

(Optional)

### Related Issues

(Optional)

### Screenshot or Screencast

(Optional)

**Comment by aliceriot** [comment]
@pdpinch I think we discussed today want to add a loading placeholder for the course home page, right?

for the course search page I think this is the only change we need to make:

![loadinganimation](https://user-images.githubusercontent.com/6207644/65056739-6f00c800-d93f-11e9-8348-6c65429de2db.png)

so that the top of the animation matches up with the top of the card list:

![corusesearchlaoded](https://user-images.githubusercontent.com/6207644/65056772-79bb5d00-d93f-11e9-9760-7b250fd20761.png)

**Comment by pdpinch** [comment]
That sounds right to me -- do you need @abdulkdawson to remove that top bar for you?

**Comment by aliceriot** [comment]
no, the loader is implemented in React

**Comment by aliceriot** [comment]
here's what it looks like to get rid of the top bar:

![topbar](https://user-images.githubusercontent.com/6207644/65057481-ab80f380-d940-11e9-97dd-4e3778d757c9.gif)

the only thing here I think is that we still show that loader when the user changes the filters, so we might want to implement a grid loader to show if the user has selected the grid view (otherwise there's a weird disconnect you can see in the gif)

**Comment by abdulkdawson** [comment]
@aliceriot @pdpinch Here is the link to the loading loop for the search grid view.

[https://projects.invisionapp.com/d/main#/console/17477251/384370991/preview](https://projects.invisionapp.com/d/main#/console/17477251/384370991/preview)
