### ISSUE TITLE
Update UX for reordering items in  learning paths

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2434]
As a user, I'd like to be able to reorder items in my learning paths, even when the learning path contains a large number of items. 

As a user, I don't expect to reorder items in my lists. 

#### Designs and Mockups

TBD

#### Acceptance Criteria:

- [x] switch to a compact design for list items when in reordering mode
- [x] don't allow reordering of lists items; only learning paths can be ordered

**Comment by abdulkdawson** [comment]
@pdpinch here is the link to the reordering design. [https://projects.invisionapp.com/d/main?origin=v7#/console/18704964/389439354/preview?scrollOffset=740](https://projects.invisionapp.com/d/main?origin=v7#/console/18704964/389439354/preview?scrollOffset=740)

**Comment by aliceriot** [comment]
I think based on our conversation yesterday we wanted to have a "compact" design for the cards - do we have a mockup of that in particular?

**Comment by aliceriot** [comment]
the pr here: https://github.com/mitodl/open-discussions/pull/2427 hasn't been merged yet btw, so we can still update the design there to whatever we want before merging.

**Comment by aliceriot** [comment]
@pdpinch just following up on this, should we go ahead and merge the implementation I have based on the current design, and then update to a more compact design later, or should we go for the compact design now?

**Comment by Ferdi** [comment]
I think we should merge #2427

**Comment by aliceriot** [comment]
cool, I just went ahead and merged that. I also already incorporated there the change to only allow re-ordering for learning paths, not for user lists.

**Comment by aliceriot** [comment]
I see that there's an updated design on invision here: https://projects.invisionapp.com/d/main#/console/18704964/396553918/preview

is that design ready to implement?

**Comment by Ferdi** [comment]
Looks good to me. Had a couple of short comments.

**Comment by aliceriot** [comment]
are we decided fully on having a reorder items -> then save workflow for this feature?

currently how it works is that the new order is saved when each item is moved.

also @rhysyngsun is currently refactoring this to deal with the pagination, so I'm going to open a PR just for the styling part because I don't want to mess up that work too much

**Comment by abdulkdawson** [comment]
@aliceriot Here is the latest mock for the Reorder Items in learning paths. [https://projects.invisionapp.com/d/main#/console/18704964/396553918/preview](https://projects.invisionapp.com/d/main#/console/18704964/396553918/preview)

**Comment by pdpinch** [comment]
@abdulkdawson @aliceriot is this done?

**Comment by aliceriot** [comment]
the styling updates are done, but haven't yet done the change to modify the saving workflow (just because it's a bigger lift and I wasn't fully sure we wanted to go for it)

**Comment by pdpinch** [comment]
@aliceriot can you remind me what the current behavior is?

**Comment by aliceriot** [comment]
here's sort of the current UX flow:

- the user clicks the reordering button
- the UI changes to reflect that: the cards get more minimal (no pictures) and a "drag handle" icon appears on their left-hand sides
- the user can drag and drop one of the cards to reorder
- when the user 'drops' the card in its new spot a request is made to the backend to save the new order. while this is in-flight the UI is greyed-out and the drag-and-drop is disabled. after the request comes back the user can interact with the UI again.

the change that is proposed that hasn't yet been implemented is sort of making it so that the user would basically turn on reordering mode, make some edits to the list order, but they wouldn't be saved until the user clicked a "save" button. so until that point the new order would just be in-memory in the user's browser (a draft order I guess we could call it). as I said above, it's just a bit of a refactor to change things around to work that way, definitely pretty simple but I didn't get a confirmation that we wanted to make that change and so didn't include it in the visual redesign PR.
