### ISSUE TITLE
Learn: set the default sort when there is no search text

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2494]
As a user, I'd like to see the most representative learning objects at the top of the page, before I enter a search term. In particular, I'd like to see free or no cost items that are available now.

#### Acceptance Criteria:

- [ ] sort first by price ascending, then availability. The first page of results should be all free courses available now. 

#### Out of Scope

- we should consider allowing the user to change the sort
- it would be nice if the sort could reflect the users profile and/or search history

**Comment by abdulkdawson** [comment]
@pdpinch Here is my recommendation for the default sort in Open. Take a look and let me know what you think.


New Users and Users not signed in:

The default sort should have the most popular free courses and programs displayed as soon as the user lands on the Open search page. These results will reflect the Learning Resources that have been clicked, searched and saved by site-wide users.


New Signed in: 

The default sort should have the most popular free courses and programs displayed as soon as the user gets to the Open search page. Since this is the first time the user is visiting the site they will begin to create a history that will be reflected in the default results upon their return visit to Open. 


Returning Users Signed in: 

By default, the user will see courses related to their previous search history along with other popular courses and programs. 
As the user continues to search and click on various learning resources they will add to their user history and altering the sorting of Learning Resources. 


All users will also have the ability to sort those results by using the “Sort By” dropdown. The “Sort By” dropdown will allow the user to sort the results by popularity, alphabetically A-Z, alphabetically Z-A and Newest.

**Comment by pdpinch** [comment]
After discussing in Slack, we decided to opt for defaulting to sorting by price ascending and then availability (now first). 

I've updated the description.

**Comment by abeglova** [comment]
After a discussion with Peter, we decide to opt for sorting by price ascending then the date the resource was added to the search
