### ISSUE TITLE
Restricted Channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#262]
As a staff member, I'd like to be able to create channels that only staff can post to. Learners would still be able to comment. A channel like this could be used for "Announcements" or by course staff who wants to focus discussion on only their own posts. 

Reddit supports restricted channels. And it supports private channels. But it doesn't support channels that do both. To support private + restricted channels, we can create a private channel and limit posting to moderators, through the open-discussions application.

**Comment by roberthouse54** [comment]
Restricted channels will be created by adding a new option in the Create New Channel modal. This will be in a section called "Who can submit posts?" The options will be "Anyone" (the default) and "Moderators only." Restricted channels will display a message in the Channel Info card that says the channel is restricted. (See mock) This issue is blocked by #263, because the design requires the "About this channel" card.

![image](https://user-images.githubusercontent.com/20047260/31397560-5419e598-adb4-11e7-9b2d-62c667d861fc.png)

![image](https://user-images.githubusercontent.com/20047260/31397297-a4219064-adb3-11e7-99b9-065d670ddd08.png)

**Comment by pdpinch** [comment]
replaced by #830
