### ISSUE TITLE
Mixup between MITx and OCW courses

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3182]
The following published OCW courses on production had 0 runs, and each had a corresponding MITX course with the same course id and multiple runs including one OCW run.  Try to determine how the courses/runs got into this state.

"PROD/15/15.071/Spring_2017/15-071-the-analytics-edge-spring-2017/", 
"PROD/3/3.090SC/Fall_2010/3-091sc-introduction-to-solid-state-chemistry-fall-2010/", 
"PROD/6/5.99/Spring_2011/6-00sc-introduction-to-computer-science-and-programming-spring-2011/"

The Analytics Edge 15.071 http://ocw.mit.edu/courses/sloan-school-of-management/15-071-the-analytics-edge-spring-2017

Introduction to Solid State Chemistry 3.091SC http://ocw.mit.edu/courses/materials-science-and-engineering/3-091sc-introduction-to-solid-state-chemistry-fall-2010

Introduction to Computer Science and Programming 6.00SC http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011

**Comment by mbertrand** [comment]
I wasn't able to recreate this problem after reimporting the courses.

**Comment by pdpinch** [comment]
We should try deleting the course(s) on RC and then run the MITx import again to see if they return.

**Comment by mbertrand** [comment]
After deleting and reimporting on RC and production, both are now identical: offered_by of "MITx" only, but still a course_id of "6.00SC"

**Comment by abeglova** [comment]
The id comes from `master_course_number` in 1.jasn in the raw data in ocw-content-storage. "6.00SC" is right

**Comment by pdpinch** [comment]
I thought the course in question was coming in with OCW and MITx tags, but the runs consisted of only MITx course runs. 

But, I don’t have a link to it anymore so I’m not sure.

**Comment by pdpinch** [comment]
Two more of these "chimera" MITx/OCW courses. On Friday 4/9 they both have a last modified date of 4/9. 

https://open.mit.edu/admin/course_catalog/course/9329/change/?_changelist_filters=q%3D3.091sc
https://open.mit.edu/admin/course_catalog/course/10011/change/?_changelist_filters=q%3D15.071 

You can spot them leaking through into OCW search because they are the only ["introductory"](https://ocwnext.odl.mit.edu/search/?l=Introductory) and ["intermediate"](https://ocwnext.odl.mit.edu/search/?l=Intermediate) courses, respectively.

**Comment by abeglova** [comment]
I was not able to reproduce the error either
