### ISSUE TITLE
Webpack builds often take a long time or fail

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3691]
### Steps to Reproduce

Run `docker-compose up`

### Expected Behavior

Within a minute or two, webpack is done building the front-end

### Actual Behavior

Occasionally, webpack takes >15 minutes or fails to complete altogether, and `docker-compose up` has to be restarted.

**Comment by ChristopherChudzicki** [comment]
Possibly related... I have noticed that `docker compose up` fails to build infinite corridor (because `ol-util` has not been built) but then if I edit an infinite corridor file (triggering a rebuild via watch) then everything is fine.  The prod build is set up with `yarn workspace foreach --topological`, where the `topological` bit ensures that dependent workspaces are build first, but I don't think the ordering is guaranteed the way I set up watch mode for local dev

**Comment by ChristopherChudzicki** [comment]
@mbertrand I believe this was cleared up by https://github.com/mitodl/open-discussions/pull/3874. If I'm wrong and it's still an issue, please re-open.
