### ISSUE TITLE
Return 404 for profiles that have been retired

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3752]
### Steps to Reproduce

1. Create an account
2. open the new account's public profile
3. retire the account
4. visit the public profile again. 

example: https://open.mit.edu/profile/01GCJESMMVFA02S2NWH63SD7N4/

### Expected Behavior

- the HTML request should return a 404, so the public profile isn't indexed by search engines 

### Actual Behavior

- the HTML page returns a 200
- the API returns a 404

### Related Issues

- some users have been creating spammy profiles, which get indexed by google. We can retire the spammy accounts, but Google doesn't stop indexing them. 

### Screenshot or Screencast

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/430126/191772556-1b8b81d1-e4e6-4a1b-80a4-1ab056242cf8.png">

**Comment by mbertrand** [comment]
This is also an issue for channels (https://open.mit.edu/c/fakechannel), fields (http://localhost:8063/infinite/fields/fakefield) and probably other pages - the api returns 404 but the page is 200.

**Comment by pdpinch** [comment]
Is there a way to address it everywhere, or do we need to modify each route separately?

**Comment by mbertrand** [comment]
This seems to be a common issue across our apps (ex: https://ocw-studio-rc.odl.mit.edu/sites/fakesite) and with React in general, when the url path format is valid (like `../users/<user_name>`) but the api response for a particular object returns a 404.  Django has already returned a 200 status for the page before the API request for a particular object is even made from the front end. @ChristopherChudzicki do you have any suggestions for dealing with this?

**Comment by ChristopherChudzicki** [comment]
AI'm still learning about SEO, so...**Question:** My understanding of search indexing is that Google (et al) crawl links in the site. So why are fake profiles being indexed? Wouldn't there need to be a link on the site somewhere to that fake profile?

https://codelabs.developers.google.com/codelabs/making-a-single-page-app-search-friendly#6 suggests two possibilities:
1. from the frontend SPA, redirect to a 404 served by django when APIs return 404
2. on the frontend SPA, add a `<meta name="robots" content="noindex">` to the page. (We are already dynamically setting some meta tags with react-helmet.)

*Aside: haven't we been using robots.txt to prevent indexing of stuff in OCW? [Google says](https://developers.google.com/search/docs/crawling-indexing/robots/intro)*:
> *A robots.txt file tells search engine crawlers which URLs the crawler can access on your site. This is used mainly to avoid overloading your site with requests; it is not a mechanism for keeping a web page out of Google. To keep a web page out of Google, [block indexing with noindex](https://developers.google.com/search/docs/crawling-indexing/block-indexing) or password-protect the page.*

**Comment by mbertrand** [comment]
Thanks Chris, I'm inclined to go with option 2 - adding a noindex metatag if a 404 is returned from an API response.  @pdpinch  are you okay with that as an alternative to the page returning a 404 status code?

**Comment by ChristopherChudzicki** [comment]
*I'm **not** suggesting we embark on SSR, just mentioning this for context.*

In order to actually return a 404 error for the HTML load at https://open.mit.edu/profile/fakeuser/¹ I think we'd need to invest in server-side rendering. Which is not a small undertaking. My understanding of SSR for SPAs is that there's a JS server running on the backend which renders the SPA. I think with Django it would works omething like:

1. An end user requests https://open.mit.edu/profile/fakeuser
2. Django requests the page from the JS server, which renders the React app.

    The JS server might make API calls to Django during the rendering process.
3. If the rendering goes ok, Django responds with a 200 and the generated HTML + js.

    If errors occur during rendering (e.g., APIs respond 404) then Django can return 404 for the HTML page.
4. Once the end user has the HTML page served by Django, routing occurs on the frontend.

Here's some library I found for setting up SSR with Django + NextJS (a js toolset for React): https://github.com/QueraTeam/django-nextjs

Adding SSR seems like a lot of effort and would have big implications across our stack. But I wanted to mention it here for context. I'm still learning about SSR, but I'm starting to understand why people say it's good for SEO.

----
¹As opposed to a 200 that redirects to a 404, or including a meta tag as a hint to Googlebot.
