### ISSUE TITLE
Assign department to MITX Online, MITx, and OLL courses

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3827]
Assign a `department` value for each `Course` imported from MITx Online (`platform='mitxonline'`), Open Learning Library (`platform='oll'`, and MITx (`platform='mitx'`).  The department number can be deduced from the course id:

`MITx+7.03.2x` -> Department number 7
`course-v1:MITxT+21A.819.2x` - Department number 21A

The full list of valid course ids is included in [this json file](https://github.com/mitodl/ocw-studio/blob/6379dc014c34dc41bfdff2fb7ce9a38cabd10983/static/js/resources/departments.json) from OCW.

Sometimes the department number won't be in the course id:
`MITx+CITE101x`

In that case, leave the field blank?

#### Designs and Mockups
The ETL `transform_course` functions for each platform are here:

[MITx Online](https://github.com/mitodl/open-discussions/blob/bd51b108b9170c7d854e57473cd3991255cf62df/course_catalog/etl/mitxonline.py#L120-L143)

[MITx, OLL](https://github.com/mitodl/open-discussions/blob/bd51b108b9170c7d854e57473cd3991255cf62df/course_catalog/etl/openedx.py#L222-L259)

Something like the following line will need to be added to each `transform_course` function:

```python
"department":  extract_department_from_id(course.get("key"))
```

#### Acceptance Criteria:

- [ ] Most MITx, OLL, and MITx Online courses will have non-null `department` values.

**Comment by JenniWhitman** [comment]
- Q: is the list from OCW static and something that we can bring over (like a list of department numbers or a dict if we need the name to display) or is it subject to change and something we should be grabbing FROM ocw?
- Q: DO we need the whole json over here or do we just need the number if the latter above?
- Looks like, as @mbertrand said, just need a transform function that takes in a string and since there's not so much a pattern for the department other than it occurring after the +, the simplest answer might just be to split the string at the + and the next . and see if that string matches any in the previous list/dict/json.

**Comment by JenniWhitman** [comment]
Since i got answers on the data question, I'm going to store the data locally for departments in `course_catalog.constants` and the transform function in `course_catalog.utils` which will take a `course` and strip the string from `+` to the first occurrence of `.` and check if that remaining string is a valid department. If so, it will attach it to the object returned by the `transform_course` function and then update teh related tests to expect a course department and add tests for department.
