### ISSUE TITLE
Paginated search API results can contain duplicate entries

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3934]
### Steps to Reproduce

Because the same search query does not always produce the same results, this is a bit hard to reproduce. It's much easier to reproduce with queries with small `total`. For example,  https://discussions-rc.odl.mit.edu/learn/search?t=Security%20Studies has ~25 total results.

1. Visit https://discussions-rc.odl.mit.edu/learn/search?t=Security%20Studies
2. Load all the results by scrolling down
3. `ctrl+f` search for `Causes and Prevention of War`. 

### Expected Behavior

All search results are unique.

### Actual Behavior

Sometimes the results include duplicates (and are probably missing some other items). (**Note: _not_ two different results with same title.**) For example, with the page above, try searching for "Causes and Prevention of War". There should be one result, but sometimes there are 2.

### Screenshot or Screencast

<img width="1099" alt="Screenshot 2023-04-11 at 11 07 32 AM" src="https://user-images.githubusercontent.com/9010790/231207200-4701ceee-cd2a-4003-9320-a8d9eecf2a2b.png">

**Comment by ChristopherChudzicki** [comment]
After talking with @abeglova a bit about how the search API works, my understanding is:
- search results are not entirely deterministic. The same query can yield different results when re-run.
- consequently, pagination doesn't work perfectly: you make a request with `{ from: 0 }`, then another with `{ from: 10 ... }`, expecting that results 0-9 won't be included. But since there's no single response for "results 0 to 9", that expectation isn't always met.

**Comment by abeglova** [comment]
I initially thought the issue was caused by different shards returning slightly different scores, but the problem persists after I restricted the search to just one shard of the course index :( The problem is that the score result is not stable between queries/pages

I'm going to try to see if using either scroll or point in time with search after
https://opensearch.org/docs/latest/search-plugins/searching-data/paginate/
https://opensearch.org/docs/latest/search-plugins/point-in-time/

Fixes the issue

**Comment by abeglova** [comment]
Since discrepancies between shards isn't the problem, I can't really explain why I don't get duplicate entries locally - just on rc and prod

**Comment by abeglova** [comment]
Ok! I played around with the scroll api and it fixes the problem but I'm worried that keeping a bunch of scroll contexts open is going to potentially use a lot of memory,

I think there is a simpler solution:

The part of the score that varies between queries is noise. Instead of sorting by score we can sort by score rounded off to the first decimal which is pretty constant between searches then use a tie breaker such as the created_on date or just the id to sort documents with essentially the same score

**Comment by abeglova** [comment]
Larger page sizes are also a good idea

**Comment by ChristopherChudzicki** [comment]
@abeglova 

> Instead of sorting by score we can sort by score rounded off to the first decimal which is pretty constant between searches then use a tie breaker such as the created_on date or just the id to sort documents with essentially the same score

That makes sense to me. The tie breaker would also solve the problems with 0-score (unscored?) searches like https://discussions-rc.odl.mit.edu/learn/search?t=Security%20Studies, right?

**Comment by abeglova** [comment]
So the zero score searches actually have scores. The score is just not displayed in the results unless there is an explicit search param or you show scores with `track_scores=True`. In that query elasticsearch still calculates the scores under the hood and sorts by them

**Comment by abeglova** [comment]
So rounding off the scores reduced the problem but did not eliminate it - there were still results that got different scores in different pages even after i tried dividing the scores by 3 (a lot since the scores were  in the 10-30 range). I also tried using search_after but that did not help since I was sorting by scores that were changing.

I figured out the actual problem though - each index on rc is divided into 2 shard but each shard is distributed over 4 nodes. I tried using the preference param to force opensearch to query the same shard between pages and that did not help because the scores were different between nodes. After I forced elasticsearch to query both the same shard and node I no longer got any duplicates. I'm confident that I got zero duplicates because the infinite search actually warns about duplicates since the way we create keys results in duplicate keys.

It appears that opensearch has different lucene indexes on different nodes - the scores were different because opensearch calculation of both the total number of documents and the number of other documents with hits differed between nodes. Opensearch uses this information about the degree to which a keyword is common in the index to calculate how much weight to give to a hit.
