### ISSUE TITLE
automatically render URLs in posts and comments with anchor tags

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#440]
In posts like https://discussions.odl.mit.edu/channel/DEDP/30 the URL at the end of the post should have been a link.

**Comment by rhysyngsun** [comment]
It looks like the post got deleted? 

Reddit and our UI support markdown, so a link can be rendered as `[Google](http://google.com)`, did the user do this and it not work?

**Comment by aliceriot** [comment]
could also be a case of users not being familiar with markdown, maybe we could add a little 'formatting help' UI that explains some basics

**Comment by pdpinch** [comment]
Since most of our users are unfamiliar with markdown, I think automatically converting 

```http://example.com/some_url``` to ```[http://example.com/some_url](http://example.com/some_url)``` is reasonble

**Comment by rhysyngsun** [comment]
I'd suggest that if we want to do this automatic conversation that we do it when the user creates the post and convert the url to markdown syntax, that way if our automatic mechanism doesn't have perfect logic for some url that the user is able to correct the formatting themselves rather than having to wait for a bug patch.

**Comment by pdpinch** [comment]
This is blocked pending a product discussion about using some kind of WYSIWYG editor.
