### ISSUE TITLE
responsive mail template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#462]
See #470 and #450 for specific examples.

**Comment by roberthouse54** [comment]
I think we should use Mailgun's email templates as a starting point, and then inline the styles using http://premailer.dialect.ca/.

See: https://github.com/mailgun/transactional-email-templates#inline-the-css

**Comment by roberthouse54** [comment]
The HTML template is attached as a zip file below. 

A few notes:

1. This template uses nested tables to create the basic white box and the overall width of the box.
2. You can stack elements on top of each other without putting them inside divs, because they have top and bottom margins of 15px. This includes paragraphs, headers, lists, etc.
3. You only need to put elements inside divs in special cases:
     - Primary buttons should be put inside a div. (because the button is an inline-block)
     - If you want to center elements, put them inside a div with class "aligncenter"
4. I believe that the footer (with unsubscribe link etc) is handled in a separate PR but I am not sure how this works.

[email_html.zip](https://github.com/mitodl/open-discussions/files/1789870/email_html.zip)
