### ISSUE TITLE
Add moderators

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#557]
As a micromasters staff member who is a channel moderator, I would like to be able to add moderators from the community to help with moderation tasks.

**Comment by pdpinch** [comment]
This should probably be a mini epic with separate issues for the back-end, REST API and front-end. It may also require some changes to MicroMasters.

**Comment by rhysyngsun** [comment]
@pdpinch I think we had previously discussed that since MM effectively owns and manages the channel, management of moderators needs to happen over there. The APIs are already in place on the OD end and in mitodl/open-discussions-client. Here's the epic for it over on MM: https://github.com/mitodl/micromasters/issues/3760

**Comment by pdpinch** [comment]
replaced by #864
