### ISSUE TITLE
Mail: anonymous profile image is missing for user's without a profile image

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#576]
![img_5587](https://user-images.githubusercontent.com/430126/38103501-76248aaa-3354-11e8-84ab-564890a51607.PNG)

**Comment by aliceriot** [comment]
So! I looked into this a little bit. The issue is not in our serializers in open-discussions but in our email template. We are sticking `post.profile_image` directly into the email. If the user has a profile image set, this will be an absolute URL because we store user profile images (in MM) in cloudfront, so the profile sync just pushes over that cloundfront URL and all is well. If the user does _not_ have a profile image set in MM, however, the `PostSerializer` will set `post.profile_image` to be `/static/images/avatar_default.png`. And yeah, then we're sticking a relative URL in an html email, and that doesn't work. So the solution is to make sure that, in the email template, we're turning the relative URL into an absolute URL.

**Comment by aliceriot** [comment]
this does mean, though, that the default profile image will be served by the open-discussions app, I'm not sure if that's what we want.

**Comment by pdpinch** [comment]
I'd really like to stop the broken images. 

Can we do a follow-up issue to push static assets like this to the CDN?

**Comment by aliceriot** [comment]
sure, or if we're not worried about the load we can just leave it be
