### ISSUE TITLE
Disable the vote buttons for anonymous users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#687]
The user needs to be logged in before they can vote on a post. 

We probably want to leave the vote button visible, since it's necessary to give the vote count context.

**Comment by aliceriot** [comment]
@robhouse do you have any thoughts on what we should do visually? I was thinking we may want to grey out the buttons a little bit, or maybe set a tooltip that says 'log in to vote' on hover or something (or on click).

**Comment by pdpinch** [comment]
We've been talking about doing something similar to what Stackoverflow does -- when an anonymous user clicks a upvote button they get a pop-up asking them to log in or sign up. The details are still in process though.

**Comment by roberthouse54** [comment]
Since we have not yet worked out what we want to do here, design-wise, and since we do not yet have the registration flow, I suggest as a preliminary step we simply disable the upvote arrows, and if a user clicks on it, we can show a tooltip saying that users need to be logged in to vote. We can then later revisit this once we have figured out the desired UX.
