### ISSUE TITLE
Drawer: Add navigation drawer to Settings page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#766]

**Comment by aliceriot** [comment]
This is complicated slightly by the navigation currently being dependent on the list of subscribed channels. It's possible to navigate to the settings page without being signed in, because we have the token-based auth that we use in the 'unsubscribe' links from the email. The token-based auth allows you to authenticate to the settings API but not the subscribed channels API, which is why the navigation drawer isn't currently present on the settings page. I'm not sure exactly how we want to handle this, but those are kind of the questions on the table.

**Comment by Ferdi** [comment]
Sounds like we need 2 different routes to access the same settings page. One for token-based auth (no side nav), and te other one for fully logged in users (with nav) ?

**Comment by pdpinch** [comment]
It looks like the nav drawer has been restored to the settings page. It's a little weird when the user isn't logged in, but I think that will be dealt with later.
