### ISSUE TITLE
Inconsistent logged in experience

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#859]
From https://odl.zendesk.com/agent/tickets/18150 but I've also heard Lucas describe a similar behavior: 

> I encounter two different login responses on discussions.odl.mit.edu. Sometimes I log in and can see all the discussion, but cannot see the blue 'new discussion' button, or any posting options. This most often happens when I navigate directly to the discussions url. I appear to be partially logged in. ??? If I first navigate to mm.mit.edu, click on dashboard (even though I am already logged in) and then navigate to discussions url, all the functionality is available. I would somewhat expect this behavior. Though today, I navigated to the dashboard first then went to discussions and still got the non functional version.

![image](https://user-images.githubusercontent.com/430126/42107206-7c2c31e4-7ba4-11e8-8d52-ccec43f39da7.png)

**Comment by rhysyngsun** [comment]
I suspect this happens when the page initially loads and your JWT token is presently expired. This causes us to initialize the app as if the user isn't logged in. Then we attempt to make an API request (e.g. the frontpage) and get a 401, at which point the app renews the JWT token with MM and is able to request private data, but some of the app (menu on top right, submit button). I think this stems from our usage of the static global `SETTINGS` to determine who the user is and if they're logged in.

This also is an issue for login/register where the user gains a logged in session. The short-term fix there has been to simply force a reload of the application with a hard url redirect.

Once the new auth flow lands, I would expect this issue to mostly go away (sessions last longer).

I still think we need to address the issue of our usage of a static global object in application state, since it's likely to cause difficulty in the future.

**Comment by pdpinch** [comment]
When would you expect this behavior to improve: after #824 is merged? after we turn on the setting to enable email login flow? or something else? 

Is there a tech debt issue that can be written to "address the issue of our usage of a static global object in application state" ?

Do we need any more details from users (Lucas and Arthur) to confirm this diagnosis? Or do I just tell them when it's fixed and wait to hear if they hit the issue again?

**Comment by rhysyngsun** [comment]
@pdpinch I'd expect this to go away after we switch over to proper django sessions, which won't happen for MM until #774 is complete.

**Comment by rhysyngsun** [comment]
This shouldn't be an issue anymore.
